### ISSUE TITLE
Recruiting Ogremon before fighting Drimogemon makes Meramon and Drimogemon unobtainable

### ISSUE THREAD

**Issue by wooguy** [challenert/digimon_world_randomizer#22]
An issue in the vanilla game but enhanced by random recruits, as the trigger for the enraged Drimogemon to change from fighting you to saying "I fixed the sign" is Ogremon joining the city. Thus if you randomly recruit Ogremon super early (from say Kunemon, Betamon or Coelamon) before even fighting Drimogemon, you can no longer obtain these two

**Comment by challenert** [comment]
Fixing this should come down to removing the randomization of a single trigger.  That should return it to the vanilla state (the bug will occur if you actually recruit ogremon before drimogemon), rather than being out of your control.
