### ISSUE TITLE
Issue with entrance to Mt Panorama random items

### ISSUE THREAD

**Issue by Zorban13** [challenert/digimon_world_randomizer#24]
State 1: Before you talk to Meramon/reach the other side of the blockade.
https://gyazo.com/fa1dcc58848131949e4ac7e04741c432
Rare item and the two common items are correctly randomised.

State 2: After talking to Meramon/reaching the other side of the blockade.
https://gyazo.com/7238a1eb749d0494bb4e41c88521902c
Rare item and the two common items are not randomised at all.

**Comment by challenert** [comment]
Duplicates issue #23, these two are symptoms of the same problem.
