### ISSUE TITLE
Starting Digimon always starts with Gabumon's stats

### ISSUE THREAD

**Issue by SydMontague** [challenert/digimon_world_randomizer#26]
It's caused by `002328 if pstat(103) != 3 then 2376` in Script ID 193, Section 55.

Changing the compared value to the ID of the first Digimon should fix this.

And while you're at it you might just as well randomize the starting stats.

**Comment by challenert** [comment]
Yes, I had considered randomizing the starting stats.  I'll look into it when I fix this.

**Comment by challenert** [comment]
Created #27 to add starter stat randomization.
