### ISSUE TITLE
Add option to un-rig slots

### ISSUE THREAD

**Issue by challenert** [challenert/digimon_world_randomizer#48]
Add an optional patch to un-rig slots to be fair (entirely skill based).  This requires a single instruction change to short-circuit the rigged part of slots:

Game memory offset `0x0008E838` should be changed from `0x108100BA` to `0x08023A1E` .

**Comment by SydMontague** [comment]
Note: this is only for Green Gym and associated gyms (e.g. Cherrymon). For other gyms a separate hack is necessary (coming soon™).

**Comment by SydMontague** [comment]
Game memory offset `0x0008D210` should be changed from `0x108100BA` to `0x08023494` for external training stations. (TRN2_REL.BIN, Green Gym is TRN_REL.BIN)

**Comment by challenert** [comment]
BIN offsets:

`0x14C8DB10` // TRN_REL.BIN (Green Gym)
`0x14C941F8` // TRN2_REL.BIN (External Stations)
