### ISSUE TITLE
Asking for ROM ?

### ISSUE THREAD

**Issue by PhoenixMT** [challenert/digimon_world_randomizer#62]
so the game keeps asking for a .bin, but all i can find online are iso of the game so I got no clue where to get a .bin file of the game am i missing something (appart from the bin files :( )  ?

**Comment by challenert** [comment]
Please do not ask where to find ROMs, as the distribution of them is not legal.

If you already have a ROM, you can extract the binary (.BIN) file from the ISO file.  I'm sure there are many tools.  ISO is just a packed format, and if you unpack that file you will have a BIN file and a CUE file.  You can then run the program on the BIN and repack it with the same CUE file.
