### ISSUE TITLE
Open Toy Town for all Digimon with "Unlock All Areas"

### ISSUE THREAD

**Issue by RaikouSRL** [challenert/digimon_world_randomizer#63]
When ticking the Unlock All Areas option in the randomizer, Toy Town remains locked without the suit evolution, i feel for consistency this should be added with Ice Sanctuary and Grey Lords as those also skip the requirement of certain Digimon making for a smoother experience

**Comment by SydMontague** [comment]
Should be fixed in the latest merge.
