### ISSUE TITLE
This tool fail to read data from my game

### ISSUE THREAD

**Issue by benjdero** [challenert/digimon_world_randomizer#77]
I've tried both the GUI and command line tools, none seems to work with my ROM, I get the following error:
> D:\Benjamin\Downloads\digimon_randomize\gui\resources\app>digimon_randomize.exe -settings settings.ini
> Reading data from D:\Benjamin\Downloads\Digimon World PSX-PAL-FR(patched).bin...
> Traceback (most recent call last):
>   File "digimon_randomize.py", line 53, in <module>
>   File "digimon\handler.py", line 811, in __init__
> IndexError: list index out of range
> [3080] Failed to execute script digimon_randomize

As the name indicate, I use a patched version of the PSX-PAL-FR ROM, which removed the game breaking bug of the Agumon not triggering his dialog lines in the french version of the game, and thus, making it impossible to get inside of the Ogre's Fortress. Is that the problem ? May it have changed all the binary offsets and made your tool unusable ?

**Comment by challenert** [comment]
I'm sorry, @benjdero, but this does not work for the PAL version of the ROM :( 

All of the offsets and patches are specifically taylored to the NTSC english version of the game.  Very sorry to disappoint!

**Comment by benjdero** [comment]
Maybe you should state this in the ReadMe.

Would it be hard to find the right offset ? How did you proceed ? I only care about the increased tech learning chances in battle and the fair wheel bonus try, and maybe the random starter.

**Comment by challenert** [comment]
It would be a *massive* effort to duplicate this for any other version.

If you only want to change those, you can probably do it by changing the
appropriate constant in the data python file.  You'd have to look at the
NTSC ROM, find that block of data, then find the same block of data in your
ROM, and update the offset to point to the exact same byte of data.  For
each thing you want to use.

**Comment by benjdero** [comment]
That's what I thought and already took a look, but it look like you can't just do a 1 to 1 conversion of all the address and expect it to work.

For example, the constant "techDataBlockOffset" use address 14D66DF4 for the NTSC version, I was able to find the same chunk of data using a simple hex editor at address 157A0864 on the PAL version.

But for the constant "techDataExclusionOffsets", I've found no similar data in the PAL version. Not sure how to proceed in that case. How have you found the right offsets at first ? Is that the "bubble" techs of in-training digimons btw ?

**Comment by challenert** [comment]
Yeah unfortunately the exclusion offsets aren't going to have the same
data.  Those are chunks of metadata created by the tool that packages the
iso/bin, and thus will be completely different between different versions
of the game.  The best I can tell you is try to find garbage data in the
middle of the appropriate correct data :/ it's not a good solution
unfortunately.

**Comment by benjdero** [comment]
Yeah there is no way to convert this for PAL with the little information I have. Most of the time the same chunk just plain doesn't exist or it is duplicated multiple time for whatever reason (spawn rate for various digimons for example).

It's not possible to do this blindly like that with just an hex editor and some "find"/"go to address".

**Comment by challenert** [comment]
Like I said, that’s really the best I can do. It’s a massive effort to find
this stuff.
