### ISSUE TITLE
Randomized tech powers may be consistently too high

### ISSUE THREAD

**Issue by rogwcamp** [challenert/digimon_world_randomizer#86]
https://github.com/challenert/digimon_world_randomizer/blob/867069b5d6feb9d829991529ecac3349a827d040/digimon/handler.py#L1635

This ^ might have a parenthesis issue if this is trying to set tech.power to 70%-130% of its original value. 
If so, it was probably meant to be:
tech.power = int( min( tech.power * ( percent  / 100 ) , 999 ) )

Didn't want to raise a pr in case it is by design.

**Comment by challenert** [comment]
First of all, thanks for your interest!

Can you give an example of where the two formulas would produce different results?  Is it a rounding thing?  I can't remember if there was a reason that I did the multiplication first or not.

**Comment by rogwcamp** [comment]
Sorry, I was mistaken! These are equivalent statements in Python.

Thanks for taking a look.
