### ISSUE TITLE
Randomize Special Evos

### ISSUE THREAD

**Issue by challenert** [challenert/digimon_world_randomizer#9]
Only natural evolutions are randomized, currently.  The death evolutions, numemon, and sukamon should at least be randomized.  Others, if possible, should be randomized as well (Kunemon, etc).  Most important is Bakemon, since his death evo is available from the start.

**Comment by challenert** [comment]
Now supporting randomizing special evolution to Monzaemon, Giromon, MetalMamemon, Bakemon, Devimon, SkullGreymon, and Phoenixmon.

**Comment by challenert** [comment]
Disassembled special evolution function:

https://github.com/SydMontague/DW1-Code/blob/master/SpecialEvolution.asm

Randomizing the remaining special evolutions should come down to modifying the return value for each of the possibilities.

**Comment by challenert** [comment]
@SydMontague I think this is only ASM thing that isn't solved and waiting for my implementation

**Comment by SydMontague** [comment]
0x000e3354 // Airdramon
0x000e3384 // Ninjamon
0x000e33bc // Monochromon
0x000e3414 // Kunemon
0x000e3460 // Coelamon
0x000e347c // Nanimon
0x000e34b0 // Vademon

Should be simple byte values.

**Comment by challenert** [comment]
Numemon probably shouldn't be randomized, since it would make Toy Town very awkward.  Sukamon could still be randomized, though.  I think that's the last one.

**Comment by challenert** [comment]
```if(load(0x13847E) >= 16 && digimonType != 0x27) { // Virus Bar
    store(0x134E50, 39) // Sukamon
    
    writePStat(5, digimonType)
    store(0x1384D6, load(0x1557F0))
    store(0x1384D8, load(0x1557F2))
    store(0x1384DA, load(0x1557E0))
    store(0x1384DC, load(0x1557E2))
    store(0x1384DE, load(0x1557E4))
    store(0x1384E0, load(0x1557E6))
    store(0x13847E, 0)
  }```
Adding Sukamon based on this information from Syd.
